[dawn]
repository = "https://dawn.googlesource.com/dawn"
chromiumVersion = "7458"

[android]
ndkVersion = "27.0.12077973"
minSdk = "29"
cmakeVersion = "3.22.1"

[ios]
deploymentTarget = "13.0"

[web]
emscriptenVersion = "6.0.0"
